---
title: "test shiny harrellplot"
output: html_notebook
---

```{r setup}
library(ggplot2)
library(data.table)
library(emmeans)
library(harrellplot)
data_path <- "../data"
source("../HarrellPlot/harrellplot.R")
source("../HarrellPlot/fit_model.R")
source("../HarrellPlot/make_formula_str.R")
```

```{r setup2}
  covcols=NULL
  rintcols=NULL
  rslopecols=NULL
fit.model='lm'
add_interaction=TRUE
interaction.group = TRUE
interaction.treatment=TRUE
mean_intervals.method='lm'
conf.mean=0.95
contrasts.method='revpairwise'
contrasts.scaling= "raw" # 'percent'
conf.contrast=0.95
adjust=FALSE
show.contrasts=TRUE
show.treatments=TRUE
display.treatment='box'
short=FALSE
show.mean=TRUE
show.dots=TRUE
horizontal=TRUE
color_palette='jco'
jtheme='minimal'
zero= TRUE
rel_height=0 # Aspect ratio of forest plot vs. box/dot plot components (0 is default)
y_label="why"
```

```{r counts}
filename <- 'Experiment 5 - Insecticide bioassay data.csv'
file_path <- paste(data_path, filename, sep='/') # for knit
count <- fread(file_path, stringsAsFactors = TRUE)
count[, Entrust:=factor(rep(c("E+","E-"), each=10), c("E-","E+"))]
count[, Hu:=factor(rep(rep(c("Hu+","Hu-"), each=5), 2), c("Hu-","Hu+"))]
x <- "Treatment"
y <- "eggs_total"
g <- NULL
data <- count
fit.model <- "glm"
glm_family <- "nb"
res <- harrellplot(x="Treatment", y="eggs_total", data=count, fit.model="glm", glm_family="nb")


x="Entrust"
y="eggs_total"
g="Hu"
data=count
res <- harrellplot(x="Entrust", y="eggs_total", g="Hu", data=count, fit.model="glm", glm_family="nb")

fit.model="glm"
glm_family="nb"
harrellplot(x="Treatment", y="Eggs", data=count, fit.model="glm", glm_family="nb")
```

```{r vole}
filename <- 'vole.txt'
file_path <- paste(data_path, filename, sep='/') # for knit
vole <- fread(file_path, stringsAsFactors = TRUE)

x <- "treatment"
y <- "lifespan"
g <- "dummy_g"
data <- vole
dt <- vole

```

```{r fly}
fn <- "fly_burst.txt"
file_path <- paste(data_path, fn, sep="/")
filename <- 'fly_burst.txt'
file_path <- paste(data_path, filename, sep='/') # for knit
fly <- fread(file_path, stringsAsFactors = TRUE)
fly[, Treatment:=factor(Treatment, c('CN', 'AA'))]

x <- "Treatment"
y <- "Vburst"
g <- "Sex"

data <- fly
dt <- fly

fit <- lm(Vburst ~ Treatment*Sex, fly)
emm <- emmeans(fit, specs=c(x,g)) 

# contrasts across levels B within level A
contrast(emm, method="revpairwise")
contrast(emm, method="revpairwise", simple = "each", combine=TRUE)
contrast(emm, method="revpairwise", simple = c("Treatment", "Sex"))
contrast(emm, method="revpairwise", simple = list("Treatment", "Sex"))

emm <- emmeans(fit, specs=c(x, NULL)) 
contrast(emm, method="revpairwise", simple = "each", combine=TRUE)

```

